# Generated by Django 3.2.8 on 2021-10-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailywage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=10)),
                ('adhar_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('documents', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='vehicles',
        ),
        migrations.AddField(
            model_name='dailywage',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.driver'),
        ),
        migrations.AddField(
            model_name='dailywage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.vehicle'),
        ),
    ]
