# Generated by Django 3.2.8 on 2021-10-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0002_auto_20211007_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
