# Generated by Django 3.2.8 on 2021-10-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0003_auto_20211007_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywage',
            name='assigned_time',
            field=models.DateTimeField(null=True),
        ),
    ]
