# Generated by Django 3.2.8 on 2021-10-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0004_dailywage_assigned_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_starting', models.CharField(max_length=50)),
                ('to_destiny', models.CharField(max_length=50)),
                ('tons', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.vehicle')),
            ],
        ),
    ]
