# Generated by Django 3.2.8 on 2021-10-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0008_alter_driver_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='assaign_and_unassaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_time', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='dailywage',
        ),
    ]
