# Generated by Django 3.2.8 on 2021-10-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0009_auto_20211008_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='document_adhar',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
