# Generated by Django 3.2.8 on 2021-10-07 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0010_driver_document_adhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assaign_and_unassaign',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carbooking.driver'),
        ),
        migrations.AlterField(
            model_name='assaign_and_unassaign',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carbooking.vehicle'),
        ),
    ]
