# Generated by Django 3.2.8 on 2021-10-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0011_auto_20211008_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assaign_and_unassaign',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carbooking.driver'),
        ),
        migrations.AlterField(
            model_name='assaign_and_unassaign',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carbooking.vehicle'),
        ),
    ]
